export const studioNav = [
  { name: 'Work', to: '/studio/work' },
  { name: 'Services', to: '/studio/services' },
  { name: 'Agency', to: '/studio/agency' },
  { name: 'Culture', to: '/studio/culture' },
] as const;

export const studioHome = {
  intro: 'We create purposeful digital experiences, products and services. For now. For what’s next.',
  introLines: [
    'We create purposeful digital experiences, ',
    'products and services. For now. For ',
    'what’s next.',
  ],
  viewProjects: 'View projects',
  featured:
    'We are a digital agency based in Bilbao with a global outlook. We combine strategy, design, communication and technology to create experiences that connect with people and generate real value for brands.',
  message1: 'Design and code\nwith concept',
  message2: 'Digital by\nnature',
  description:
    'We get involved in every project as part of the team, bringing strategic vision, technical expertise, and a way of working that adapts to each brand’s pace and needs.',
  discoverAgency: 'Discover the agency',
  fractured: 'Digital by nature',
  fracturedMobile: 'nature',
  servicesIntro:
    'In a changing environment, we create digital solutions that help brands move forward, adapt and endure. Each project drives their evolution with vision, focus and results.',
  media: '/images/studio/home-brand-media.webp',
  agencyImage: '/images/studio/home-agency.webp',
  services: [
    { no: '01', before: 'Web', after: 'experience', href: '/studio/services', image: '/images/studio/home-web-experience.webp' },
    { no: '02', before: 'Digital product', after: 'and service', href: '/studio/services', image: '/images/studio/home-digital-product.webp' },
    { no: '03', before: 'Branding', after: '', href: '/studio/services', image: '/images/studio/home-branding.webp' },
    { no: '04', before: 'Social', after: 'and campaigns', href: '/studio/services', image: '/images/studio/home-social.webp' },
  ],
  projects: [
    { name: 'Orbea', desc: 'An app to extend the Orbea experience beyond the purchase', image: '/images/studio/work-02-c741168f8b.webp' },
    { name: 'Athletic Club', desc: "Renewal of Athletic Club's digital ecosystem, a strategy to reconnect with fans", image: '/images/studio/work-09-04cc65b5be.webp' },
    { name: 'Enerblock', desc: 'Redefining the brand that aims to shape the industrialised and digital future', image: '/images/studio/work-01-78903b7285.jpg' },
    { name: 'Conservas Serrats', desc: 'Building an authentic brand territory capable of preserving the essence of Serrats', image: '/images/studio/work-06-de43a9b79d.webp' },
    { name: 'CAF', desc: 'CAF, a website promoting sustainable mobility', image: '/images/studio/work-03-66cace5e7f.webp' },
  ],
  seeAll: 'See all projects',
  cultureTitle: 'Culture',
  cultureIntro:
    'The space where we share experiences, ideas and explorations on strategy, design, communication and technology. We talk about life and our day-to-day experiences.',
  cultureMore: 'View more',
  contact:
    "And now it's time to talk about your project. Tell us more and let's make it happen.",
  shallWeTalk: 'Shall we talk?',
  moreProjects: 'I would like to keep seeing more projects',
} as const;

export const studioWork = {
  title: 'Work',
  intro: 'We design customized products, services and digital experiences, combining communication, design and technology in a strategic way, creating innovative solutions for brands.',
  introLines: [
    'We design customized products, services and digital',
    'experiences, combining communication, design and',
    'technology in a strategic way, creating innovative',
    'solutions for brands.',
  ],
  services: [
    { id: 'all', label: 'All' },
    { id: 'web', label: 'Web experience' },
    { id: 'product', label: 'Digital product and service' },
    { id: 'branding', label: 'Branding' },
    { id: 'social', label: 'Social and campaigns' },
  ],
  sectors: [
    { id: 'all', label: 'All' },
    { id: 'culture', label: 'Culture' },
    { id: 'industry', label: 'Industry' },
    { id: 'sport', label: 'Sport' },
    { id: 'food', label: 'Food' },
    { id: 'energy', label: 'Energy' },
    { id: 'mobility', label: 'Mobility' },
    { id: 'tourism', label: 'Tourism' },
  ],
  items: [
    { name: 'Bilbao Fine Arts Museum Foundation', desc: 'A new way of seeing, experiencing and engaging with the Bilbao Fine Arts Museum', image: '/images/studio/work-00-d4df6aa2c6.webp', service: 'web', sector: 'culture' },
    { name: 'Enerblock', desc: 'Redefining the brand that aims to shape the industrialised and digital future', image: '/images/studio/work-01-78903b7285.jpg', service: 'branding', sector: 'industry' },
    { name: 'Orbea', desc: 'An app to extend the Orbea experience beyond the purchase', image: '/images/studio/work-02-c741168f8b.webp', service: 'product', sector: 'sport' },
    { name: 'CAF', desc: 'CAF, a website promoting sustainable mobility', image: '/images/studio/work-03-66cace5e7f.webp', service: 'web', sector: 'mobility' },
    { name: 'Lagunklik', desc: 'A digital ecosystem geared towards creating new business opportunities', image: '/images/studio/work-04-e878924538.webp', service: 'web', sector: 'industry' },
    { name: 'JMA', desc: 'Digitization of the leader in key duplication', image: '/images/studio/work-05-5c56caf9c7.webp', service: 'product', sector: 'industry' },
    { name: 'Conservas Serrats', desc: 'Building an authentic brand territory capable of preserving the essence of Serrats', image: '/images/studio/work-06-de43a9b79d.webp', service: 'branding', sector: 'food' },
    { name: 'Icoben', desc: 'Transforming a functional brand into an aspirational benchmark in the kitchen sector', image: '/images/studio/work-07-548419f425.webp', service: 'branding', sector: 'industry' },
    { name: 'RDT', desc: 'Bringing order, clarity and meaning to a complex brand', image: '/images/studio/work-08-0584c0132f.jpg', service: 'branding', sector: 'industry' },
    { name: 'Athletic Club', desc: 'Renewal of Athletic Club\'s digital ecosystem, a strategy to reconnect with fans', image: '/images/studio/work-09-04cc65b5be.webp', service: 'web', sector: 'sport' },
    { name: 'Sharma Catering', desc: 'The recipe for boosting the social media presence of Sharma Catering, Grupo Ausolan\'s high-end gastronomic experience brand', image: '/images/studio/work-10-78c8ba77d6.webp', service: 'social', sector: 'food' },
    { name: 'Ausolan', desc: 'Ausolan, connecting with the legacy and future of a leading cooperative.', image: '/images/studio/work-11-77cb060d0e.jpg', service: 'branding', sector: 'food' },
    { name: 'Lasai', desc: 'A website to navigate with calm. Generating commercial opportunities in the nautical sector through the digital channel', image: '/images/studio/work-12-92b6d51177.webp', service: 'web', sector: 'tourism' },
    { name: 'Urdaibai Biosphere Reserve', desc: 'From local to digital: km0 technology for sustainable tourism in Urdaibai', image: '/images/studio/work-13-ee580ed8a1.webp', service: 'web', sector: 'tourism' },
    { name: 'BiscayTIK', desc: 'Boosting institutional communication through naming and visual identity', image: '/images/studio/work-14-d6ef402367.webp', service: 'branding', sector: 'culture' },
    { name: 'Zeid Fest', desc: 'An app that elevates the ZEID Fest experience, connecting people with their passions', image: '/images/studio/work-15-51e686ef9f.webp', service: 'product', sector: 'culture' },
    { name: 'Getxo Kultura', desc: 'New digital asset that connects the cultural fabric of Getxo, a space to promote the cultural proposal of the town and encourage citizen participation', image: '/images/studio/work-16-2367abc35e.webp', service: 'web', sector: 'culture' },
    { name: 'Café Fortaleza', desc: 'Social media strategy and management for Café Fortaleza, connecting with people through creativity and valuable content.', image: '/images/studio/work-17-7bca4a3c61.webp', service: 'social', sector: 'food' },
    { name: 'Bellota', desc: 'Cross-cutting digital strategy of social networks. Generating relationships with the professional public in the world of agriculture and construction.', image: '/images/studio/work-18-08021043a3.webp', service: 'social', sector: 'industry' },
    { name: 'Guuk', desc: 'We connect with what unites us, Kirolapp, a platform for the digitalisation of sports clubs.', image: '/images/studio/work-20-4b752e758b.jpg', service: 'product', sector: 'sport' },
    { name: 'Abus', desc: 'Security made in Germany, social media strategy and plan for a brand with 100 years of history', image: '/images/studio/work-21-8c90058038.webp', service: 'social', sector: 'industry' },
    { name: 'Last Tour', desc: 'The power of music, the corporate website for a leading company in the sector', image: '/images/studio/work-19-5fd057b892.png', service: 'web', sector: 'culture' },
    { name: 'Iberdrola', desc: 'Iberdrola Anomalies App: productivity in the energy sector through user experience and integration capabilities', image: '/images/studio/work-22-4ce1a60749.webp', service: 'product', sector: 'energy' },
  ],
} as const;

export const studioServices = {
  title: 'Services',
  intro: "We integrate strategic, creative and technological capabilities to build valuable relationships between brands and their audiences, creating a positive and lasting impact on people's lives.",
  introLines: [
    'We integrate strategic, creative and technological',
    'capabilities to build valuable relationships between',
    'brands and their audiences, creating a positive and',
    'lasting impact on people’s lives.',
  ],
  figure: '/images/studio/services-00-06f13588d9.webp',
  fractured: 'Design & Code',
  offerings: [
    { no: '01', slug: 'web-experience', name: 'Web experience', subtitle: 'Design and dev', copy: 'We develop unique digital experiences, from websites and customer spaces to e-commerce platforms and B2B tools. Each asset is designed to generate tangible results and create experiences that make the brand unique.', items: ['Digital strategy', 'Corporate website', 'Ecommerce', 'Customer platforms', 'Recruitment & CRO'], projects: ['Athletic Club', 'CAF', 'Lagunklik', 'Getxo Kultura', 'Last Tour'] },
    { no: '02', slug: 'digital-product-and-service', name: 'Digital product and service', subtitle: 'First human design', copy: 'We create immersive experiences that put people at the centre, bring distinction to the brand and respond to business objectives. We work with methodologies and tools tailored to each project to provide the greatest value and speed in activation and implementation.', items: ['Design of digital experiences and products', 'Technology consultancy', 'Customised technological development', 'Digital transformation'], projects: ['Orbea', 'JMA', 'Zeid Fest', 'Guuk', 'Iberdrola'] },
    { no: '03', slug: 'branding', name: 'Branding', subtitle: 'Becoming who we’re meant to become', copy: 'We accompany brands from where they are today to where they are destined to be tomorrow. We align vision and action, purpose and experience, so that every point of contact becomes a real opportunity to generate value.', items: ['Brand diagnosis and strategy', 'Brand identity', 'Activation and scalability'], projects: ['Enerblock', 'Conservas Serrats', 'Icoben', 'RDT', 'BiscayTIK'] },
    { no: '04', slug: 'social-and-campaigns', name: 'Social and campaigns', subtitle: 'Content creators that build brands culture', copy: 'Conceptualising an idea, transforming a brand\'s key values and messages into a campaign, choosing the channels, producing and developing the assets that allow us to create that click. We are all about doing, measuring, rethinking and intervening.', items: ['Strategy', 'Social Media', 'Campaigns', 'Brand & Business Ads'], projects: ['Sharma Catering', 'Ausolan', 'Café Fortaleza', 'Bellota', 'Abus'] },
  ],
} as const;

export const studioAgency = {
  title: 'Agency',
  intro: 'We are digital by nature. We create real connections between brands and people. Unique and authentic connections, the kind that transcend the screen. The kind that become experiences that transform and endure. Because we know that behind every project there are stories, desires and goals that deserve to come true.',
  introLines: [
    'We are digital by nature. We create real connections',
    'between brands and people. Unique and authentic',
    'connections, the kind that transcend the screen.',
    'The kind that become experiences that transform',
    'and endure.',
  ],
  teamIntro: 'We are a digital agency formed by a team of more than 30 people. United in our diversity, we work with a common purpose: to transform ideas into meaningful digital solutions.',
  teamBody: 'We are driven by ingenuity, curiosity and attention to detail. Here, each person contributes their own perspective, adding insights that make each project unique and meaningful.',
  portrait: '/images/studio/agency-00-659634a30a.webp',
  capabilitiesFigure: '/images/studio/agency-03-4ac86a73ac.jpg',
  team: [
    { name: 'Laura Carazo', role: 'CEO' },
    { name: 'Nagore Frias', role: 'COO' },
    { name: 'Leire Luengo', role: 'Account Director' },
    { name: 'Igor Nieto', role: 'CTO' },
    { name: 'Anaitz Cid', role: 'Art Director' },
    { name: 'Patricia Martínez', role: 'Strategy & Communication Director' },
    { name: 'Eneko Quintana', role: 'Creative Director' },
    { name: 'Danilo Triana', role: 'Brand Director' },
    { name: 'Aitor Markaida', role: 'Designer' },
    { name: 'Amaia Cano', role: 'Strategic & UX Designer' },
    { name: 'Anne Sada', role: 'Designer' },
    { name: 'Enara Etxaniz', role: 'Software Engineer' },
    { name: 'Esther Cazorla', role: 'Agency Processes & Operations' },
    { name: 'Esti Sedano', role: 'Social & Content Specialist' },
    { name: 'Gorka Muñoz', role: 'Front-end Developer' },
    { name: 'Iker Melero', role: 'Software Engineer' },
    { name: 'Iker Ruiz', role: 'Motion Grapher' },
    { name: 'Imanol Arenaza', role: 'Front-end Developer' },
    { name: 'Iñigo Herrero', role: 'Front-end Developer' },
    { name: 'Irune Arieta-araunabeña', role: 'Accountant' },
    { name: 'Jaime Polo', role: 'Designer' },
    { name: 'Jon Blanco', role: 'Filmmaker' },
    { name: 'Jon Ledesma', role: 'Data & Performance Manager' },
    { name: 'Jone Vispo', role: 'Performance & Data Analyst' },
    { name: 'Marcelo Verissimo', role: 'Filmmaker' },
    { name: 'Myriam Redondo', role: 'Lead Front-end Developer' },
    { name: 'Naiara Bordería', role: 'Creative & UI Designer' },
    { name: 'Nerea Gómez', role: 'Software Engineer' },
    { name: 'Oskar Gezuraga', role: 'Creative & Account Manager' },
    { name: 'Raquel Romero', role: 'Designer' },
    { name: 'Valeria Marcos', role: 'Social & Content Specialist' },
    { name: 'Zuriñe Gómez', role: 'Creative and Content Specialist' },
  ],
  capabilities: [
    { no: '01', name: 'Strategy', items: ['Research & benchmarking', 'Positioning', 'Brand, digital & business strategy', 'Experience & usability audit', 'Analytics, KPIs & data'] },
    { no: '02', name: 'Content', items: ['Content strategies', 'Branded content', 'SEO & GEO', 'Copywriting', 'Campaigns', 'UX writing', 'Social media'] },
    { no: '03', name: 'Brand and production', items: ['Brand architecture', 'Visual, verbal and sensory identity', 'Art direction', 'Graphic production'] },
    { no: '04', name: 'Experience design', items: ['UX research', 'Interface design', 'Design systems', 'Prototyping'] },
    { no: '05', name: 'Technology', items: ['Front-end development', 'Custom platforms', 'CMS', 'Performance'] },
  ],
  vision: [
    { name: 'One to one', copy: 'We believe that the most relevant brands are built with and for people. That is why we listen, understand and collaborate with empathy, sharing the same vision with those who trust us.', image: '/images/studio/agency-01-9b4387d5aa.webp' },
    { name: 'Experience and background', copy: 'More than 15 years of experience have given us a clear and practical vision in sectors such as industry, energy, tourism, culture, sport, health, food and retail.', image: '/images/studio/agency-05-6ff4e85875.webp' },
    { name: 'Strategic allies', copy: 'We believe in relationships based on trust, collaboration and mutual commitment. We get involved from day one, contributing vision, judgement and foresight.', image: '/images/studio/agency-06-c2c1790069.webp' },
    { name: 'Design with purpose', copy: 'We understand design as a transformative tool: capable of generating impact, influencing people and also business results.', image: '/images/studio/agency-07-a0986e9d3f.webp' },
    { name: 'Technological criteria', copy: 'We use the latest tools, frameworks, and programming languages. We test them and evaluate their suitability for each of the projects we work on.', image: '/images/studio/agency-08-a3c200dcfa.webp' },
    { name: 'Data intelligence', copy: 'We rely on data to make better decisions. We observe, analyse and measure to understand what works and optimise every action.', image: '/images/studio/agency-09-d698de808a.webp' },
  ],
  clients: ['Athletic Club', 'Ausolan', 'Bellota', 'Bilbao Fine Arts Museum Foundation', 'CAF', 'Café Fortaleza', 'Eroski', 'Euskaltel', 'Fagor', 'Getxo Kultura', 'Iberdrola', 'Icoben', 'Irizar', 'Kimovil', 'Lagun Aro'],
} as const;

export const studioCulture = {
  title: 'Culture',
  intro: 'The space where we share ideas and explorations about design, technology and business. We talk about life and our day to day at the agency.',
  introLines: [
    'The space where we share ideas and explorations',
    'about design, technology and business. We talk',
    'about life and our day to day at the agency.',
  ],
  gallery: [
    '/images/studio/culture-00-3cb950d06a.webp',
    '/images/studio/culture-01-a0fafff012.webp',
    '/images/studio/culture-02-28617994a5.webp',
    '/images/studio/culture-03-9b1959596b.jpg',
    '/images/studio/culture-04-cee2fd94be.webp',
    '/images/studio/culture-05-78f6f17f4b.webp',
    '/images/studio/culture-07-e66973f995.webp',
    '/images/studio/culture-08-a9347fbc2d.webp',
  ],
  notes: [
    { date: '2026.07', read: '7min', title: 'An X-ray of B2B. We partnered on ToBeInB2B, the industry\'s leading research study.', featured: true, image: '/images/studio/culture-00-3cb950d06a.webp' },
    { date: '2026.07', read: '7min', title: 'We are DANOK: the ecosystem redefining how we solve today’s and tomorrow’s challenges.', featured: false, image: '/images/studio/culture-01-a0fafff012.webp' },
    { date: '2026.06', read: '7min', title: 'Two Laus, a motionless Uber, and a blunt object', featured: false, image: '/images/studio/culture-02-28617994a5.webp' },
    { date: '2026.04', read: '4min', title: 'Award for a Brand-Building Approach Through Content', featured: false, image: '/images/studio/culture-03-9b1959596b.jpg' },
    { date: '2026.01', read: '3min', title: 'A toast to 2026 and everything we’ve lived', featured: false, image: '/images/studio/culture-04-cee2fd94be.webp' },
    { date: '2025.11', read: '5min', title: 'Naming: when choosing the right name makes all the difference', featured: false, image: '/images/studio/culture-05-78f6f17f4b.webp' },
    { date: '2025.08', read: '12min', title: 'Transforming the digital universe with Astro', featured: false, image: '/images/studio/culture-06-6f16a08855.webp' },
    { date: '2025.06', read: '7min', title: 'Figma & Workoholics, the perfect collaborative design tandem', featured: false, image: '/images/studio/culture-07-e66973f995.webp' },
    { date: '2025.06', read: '3min', title: 'Digital by nature', featured: false, image: '/images/studio/culture-08-a9347fbc2d.webp' },
    { date: '2025.04', read: '10min', title: 'Technological retrospective in a changing ecosystem', featured: false, image: '/images/studio/culture-09-fe6de937e8.jpg' },
    { date: '2024.07', read: '2min', title: 'A day in Barcelona and a bronze Laus to the best app', featured: false, image: '/images/studio/culture-10-9a8281aa30.webp' },
    { date: '2023.12', read: '5min', title: 'The penultimate vermouth prepared', featured: false, image: '/images/studio/culture-11-25e3bcdaf8.webp' },
    { date: '2023.10', read: '2min', title: 'Workoholics X Irontec', featured: false, image: '/images/studio/culture-12-b6c194dd60.webp' },
    { date: '2023.07', read: '5min', title: 'Long live Work in Progress', featured: false, image: '/images/studio/culture-13-997b75a2a0.webp' },
    { date: '2023.04', read: '10min', title: 'How to build ultra-fast and manageable websites with Astro and Strapi', featured: false, image: '/images/studio/culture-14-d8a781b27c.webp' },
    { date: '2023.03', read: '1min', title: 'We are many things. We are bad bitches.', featured: false, image: '/images/studio/culture-15-6082564ccb.webp' },
    { date: '2023.01', read: '2min', title: 'Everything will be okay', featured: false, image: '/images/studio/culture-12-b6c194dd60.webp' },
    { date: '2022.07', read: '7min', title: 'Friction with digital products, a symptom of poor UX', featured: false, image: '/images/studio/culture-13-997b75a2a0.webp' },
    { date: '2022.05', read: '3min', title: 'Work in progress, a space for celebrating creativity', featured: false, image: '/images/studio/culture-14-d8a781b27c.webp' },
    { date: '2022.03', read: '6min', title: 'A view on the state of JavaScript', featured: false, image: '/images/studio/culture-08-a9347fbc2d.webp' },
    { date: '2021.08', read: '2min', title: 'Work, Sweet Work', featured: false, image: '/images/studio/culture-14-d8a781b27c.webp' },
    { date: '2021.07', read: '3min', title: 'Celebration report: Ten years of Workoholics', featured: false, image: '/images/studio/culture-15-6082564ccb.webp' },
  ],
} as const;
